### ISSUE TITLE
specify server address

### ISSUE THREAD

**Issue by caywin25** [bqv/weechat-xmpp#8]
Hello,

Is it possible to specify ip address xmpp server when we configure account with : `/account add <foo>` ?
I would like to use my local server.

Thank you

**Comment by bqv** [comment]
I don't think it can right now, but I'll maybe add that soon

**Comment by caywin25** [comment]
Ok thank you

**Comment by caywin25** [comment]
For configuring account, we must set : /account add <jid> ? 

Right ?
